### ISSUE TITLE
Error loading GnomeBluetooth

### ISSUE THREAD

**Issue by MaKaNu** [RoccoRakete/hyprland-dots#1]
I don't use Bluetooth on my system, but this error pops up after launching ags:

```bash
(com.github.Aylur.ags:95404): Gjs-Console-CRITICAL **: 20:42:47.293: Error: Requiring GnomeBluetooth, version 3.0: Typelib file for namespace 'GnomeBluetooth', version '3.0' not found
@resource:///com/github/Aylur/ags/service/bluetooth.js:4:28
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```

I tried to identify the problem, but failed. I tried to install gnome-bluetooth (even I don't need it) but failed again.

**Comment by RoccoRakete** [comment]
Have you tried `ags --clear-cache`?

**Comment by MaKaNu** [comment]
tried now but didn't find .cache/ags

**Comment by RoccoRakete** [comment]
Try creating it then. 
If all the dependencies are met, it works, you could also try rebooting.

**Comment by MaKaNu** [comment]
Since your dependencies are only ags and hyperland I think I have everything to go, but also after restart same issue. I don't know but this error trace is hard to understand, since it doesn't point anywhere near the issue

**Comment by RoccoRakete** [comment]
Yes this is a general dependency of ags. There is not much I can do about that for now. If you installed gnome-bluetooth, this dependency should be fulfilled.  

Edit: You can remove the Bluetooth functionality, if you don't need it anyways.

**Comment by MaKaNu** [comment]
okay seems you are right. I didn't bothered BT until now. I've installed `gnome-bluetooth-3.0` and it seems to work now. The aur package is listing it as optional.

**Comment by RoccoRakete** [comment]
Great to hear!
