### ISSUE TITLE
is arch still supported ?

### ISSUE THREAD

**Issue by meduk0** [RoccoRakete/hyprland-dots#2]
i am an arch user i liked your dotfiles and as i doesn't have enough time  for a rice i just look into your install script (it looked like an arch for me but i doesn't find any ags directory to use on .I know you are migreating to nixos and i will apreciate if you keep the arch stuff or send it to me

**Comment by RoccoRakete** [comment]
Yes they are are. 

But you need to place the config files in .config on your own. 
They are located [here](https://github.com/RoccoRakete/hyprland-dots/tree/main/nixos/hosts/laptop/home-dotfiles-laptop) and [here](https://github.com/RoccoRakete/hyprland-dots/tree/main/nixos/global-dotfiles/swaylock)

You can just install all the needed dependencies by copy and paste from the existing installscript.

**Comment by meduk0** [comment]
Yeah i did it i just use your script with a lot of changes and got everything working nice dots btw .Sorry for the issue if it is a problem i can delete it .Thx for the good dots

**Comment by RoccoRakete** [comment]
> Yeah i did it i just use your script with a lot of changes and got everything working nice dots btw .Sorry for the issue if it is a problem i can delete it .Thx for the good dots

No problem. I'm happy this works for you!
